GET http://localhost:3000/first_contact.json
###
GET http://localhost:3000/all_contacts.json
###
POST http://localhost:3000/contacts
content-type: application/json

{
  "first_name": "John",
  "last_name": "Gallo",
  "email": "jgallo@email.com",
  "phone_number": "333-333-3333",
  "address": "120 S. LaSalle St, Chicago, IL"
}